print("Hello" + " World")
print("Hi! " * 3)
print("Hello"[1:4])
print("python".upper())
print("PYTHON".lower())
print("a,b,c".split(","))
print("-".join(["a", "b", "c"]))
print("hello world".replace("world", "Python"))
print("banana".count("a"))
